# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [ ]:
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10

In [ ]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array

In [ ]:
np.size(x)

10

#### 5.  How to get the documentation of the numpy add function from the command line? 

In [ ]:
help(np)

Output hidden; open in https://colab.research.google.com to view.

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [ ]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49

In [ ]:
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last)

In [ ]:
x = np.arange(10,50)
x[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
x = np.arange(0,9)
x = np.reshape(x,(3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [ ]:
x = np.array([1,2,0,0,4,0])
x = np.nonzero(x)
x

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix

In [ ]:
x = np.eye(3,3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [ ]:
x = np.random.random((3,3,3))
x

array([[[3.29072048e-01, 6.92484789e-01, 2.22907711e-02],
        [4.25895794e-01, 6.78377496e-02, 9.61568093e-01],
        [4.22342293e-02, 6.03205895e-01, 5.91565636e-01]],

       [[4.87931479e-05, 7.01789753e-01, 7.67401932e-01],
        [8.97415090e-01, 1.05960438e-01, 8.55055510e-01],
        [9.29435493e-01, 7.63022715e-01, 6.75770590e-01]],

       [[6.84219163e-01, 3.96249256e-01, 3.17494277e-01],
        [2.38651508e-01, 8.60720112e-01, 5.64047575e-01],
        [4.52996196e-01, 9.21586492e-01, 6.78057108e-01]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
x = np.random.random((10,10))
print(x)
print(np.min(x))
print(np.max(x))

[[0.96216843 0.42062271 0.13658231 0.87036204 0.79783453 0.25053636
  0.7508049  0.2434892  0.93963819 0.89515353]
 [0.37664007 0.02772791 0.14315799 0.44726982 0.29756516 0.46763308
  0.2844939  0.96157274 0.99372052 0.95435881]
 [0.78467872 0.77784996 0.60086754 0.93356837 0.68135869 0.95862167
  0.96003597 0.93215675 0.9900875  0.11827475]
 [0.00460415 0.62883633 0.44092787 0.0683923  0.8688355  0.5284819
  0.41014406 0.2178855  0.88851327 0.20998951]
 [0.17449979 0.1520313  0.13760586 0.05545984 0.17444755 0.27799564
  0.61905409 0.14724083 0.66137658 0.24584526]
 [0.94629935 0.96531129 0.65337519 0.35888553 0.42862497 0.31995741
  0.09389284 0.48828855 0.54682019 0.83839225]
 [0.65122045 0.95033731 0.0024021  0.07118995 0.18380853 0.8155663
  0.50033146 0.9390919  0.30284413 0.66946897]
 [0.4476592  0.07420894 0.04123616 0.64709598 0.04242336 0.17094396
  0.41917761 0.31714969 0.28385769 0.04591875]
 [0.77388758 0.78857542 0.67712641 0.70576869 0.14059076 0.78807541
  0.17246516 0

#### 14. Create a random vector of size 30 and find the mean value

In [ ]:
x = np.random.random(30)
print(x)
print(np.mean(x))

[0.78127006 0.60113378 0.73492665 0.65453412 0.10515992 0.24774756
 0.4377345  0.76337165 0.21384684 0.04482846 0.85404399 0.91574982
 0.599602   0.73774885 0.65857449 0.01826966 0.71155045 0.92778969
 0.28276092 0.37902673 0.28257378 0.93832445 0.25876257 0.22142369
 0.92778552 0.54479338 0.98433711 0.66343197 0.14753802 0.41657808]
0.5351739575428301


#### 15. Create a 2d array with 1 on the border and 0 inside

In [ ]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array?

In [ ]:
x = np.ones((5,5))
x = np.pad(x,1,'constant',constant_values = 0)
x

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan

nan

In [ ]:
np.nan == np.nan

False

In [ ]:
np.inf > np.nan

False

In [ ]:
np.inf - np.nan

nan

In [ ]:
np.nan in set([np.nan])

True

In [ ]:
0*3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
x = np.diag([1,2,3,4],-1)
x

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
x = np.zeros((8,8),dtype=int)
x[::2,1::2] = 1
x[1::2,::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
6*7*8

336

In [ ]:
x = np.arange(0,(6*7*8))
x = np.reshape(x,(6,7,8))
print(x)
np.unravel_index(99, (6,7,8))

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

(1, 5, 3)

(1, 5, 3)